package de.thb.koma.repository.sparql;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {

    @Test public void testServerStartStop(){
        Main main = new Main();
        main.server();
    }
}
