package de.thb.koma.repository.sparql;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class SparqlFusekiTest {
/*
    @Test public void testServerStartStop(){
        SparqlFuseki fuseki = new SparqlFuseki();
        fuseki.server();
    }
*/
}
