package de.thb.koma.repository.sparql;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.apache.jena.atlas.web.TypedInputStream;
import org.apache.jena.base.Sys;
import org.apache.jena.fuseki.Fuseki;
import org.apache.jena.fuseki.embedded.FusekiServer;
import org.apache.jena.fuseki.server.DataService;
import org.apache.jena.fuseki.server.OperationName;
import org.apache.jena.query.*;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.riot.RDFDataMgr;
import org.apache.jena.riot.RDFLanguages;
import org.apache.jena.riot.web.HttpOp;
import org.apache.jena.sparql.core.DatasetGraph;
import org.apache.jena.sparql.core.DatasetGraphFactory;
import org.apache.jena.util.FileManager;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;

import static org.apache.jena.sparql.vocabulary.VocabTestQuery.query;
import static org.junit.Assert.assertEquals;

public class SparqlFusekiTest {

    String uriService = "http://localhost:3030/ds/data";
    String uriKoma = "https://s3-us-west-2.amazonaws.com/ontology.thb.de/koma-complex.owl";
    String miniQuery = "SELECT ?s ?p ?o WHERE {\n" +
            "  ?s ?p ?o\n" +
            "}";
            String querySimple = "" +
            "PREFIX owl: <http://www.w3.org/2002/07/owl#>\n" +
            "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n" +
            "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n" +
            "\n" +
            "SELECT ?comp WHERE {\n" +
            "\t?comp rdf:type owl:Class .\n" +
            "}\n" +
            "ORDER BY ?label";
    String competencyQuery = "" +
            "PREFIX owl: <http://www.w3.org/2002/07/owl#>\n" +
            "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n" +
            "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n" +
            "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n" +
            "PREFIX koma: <https://s3-us-west-2.amazonaws.com/ontology.thb.de/koma-complex.owl#>\n" +
            "\n" +
            "\n" +
            "SELECT ?comp ?learn\n" +
            "  \tWHERE {\n" +
            "\t\t?comp rdf:type koma:Competency  .\n" +
            "\t\t?crec koma:associatedCompetency ?comp .\n" +
            "\t\t?learn rdf:type koma:Learner .\n" +
            "\t\t?crec koma:creator ?learn .\n" +
            "}\n" +
            "ORDER BY ASC (?comp) ";
    FusekiServer server;
    @Before public void ctlBeforeTest(){
        Dataset ds = DatasetFactory.createTxnMem();
        //Dataset ds = DatasetFactory.createMem();
        //DatasetGraph dsg = DatasetGraphFactory.createTxnMem();
        //DataService dSrv = new DataService(dsg);
        //dSrv.addEndpoint(OperationName.GSP_R, "upload");
        server = FusekiServer.create()
                .setPort(3030)
                //.add("/dsrv", dSrv)
                //.setStaticFileBase("resources/")
                //.parseConfigFile("resources/config.ttl")
                .add("/ds", ds)
                .build();
        server.start();
    }
    @After public void ctlAfterTest(){
        server.stop();
    }

    @Test public void uploadFileFromWWW(){
        Model model = FileManager.get().loadModel(uriKoma, "TURTLE");
        model.write(new PrintWriter(System.out));
    }
    @Test public void serveFile(){

        Model m = ModelFactory.createDefaultModel() ;
        TypedInputStream in = HttpOp.execHttpGet(uriService, "text/turtle") ;
        RDFDataMgr.read(m, in, RDFLanguages.contentTypeToLang(in.getMediaType()) ) ;
        // which is is effectively :
//        DatasetAccessor du = DatasetAccessorFactory.createHTTP(serviceREST) ;
//        Model m = du.getModel() ;
        assertEquals(1, m.size()) ;
    }


    @Test public void uploadLocalOWLToFuseki(){
        Model defModel = ModelFactory.createDefaultModel();
        try(FileInputStream in = new FileInputStream("/home/dado/projs/ba/sacwa/sparql/src/main/resources/koma-complex.owl")){
            defModel.read(in, null, RDFLanguages.strLangTurtle);// TTL
        } catch (IOException e) {
            e.printStackTrace();
        }
        defModel.write(new PrintWriter(System.out)); // works


        DatasetAccessor accessor = DatasetAccessorFactory.createHTTP("http://localhost:3030/ds/query");
        accessor.add(defModel);

        QueryExecution queryExecution = QueryExecutionFactory.create(miniQuery);
        ResultSet resultSet = queryExecution.execSelect();
        resultSet.getResultVars().forEach(System.out::println);

        server.stop();
    }




}
/*
    @Test public void queryExternal(){
        InputStream in;
        DatasetAccessor accessor = DatasetAccessorFactory
                .createHTTP(uriService)
                .putModel(ModelFactory
                        .createDefaultModel()
                        .read(in, uriKoma, "RDF/XML"));
    }
    */
/*
    @Test public void embedded_01() {
        DatasetGraph dsg = dataset() ;
        int port = 3330 ;   // Default port.
        FusekiServer server = FusekiServer.create().add("/ds", dsg).build() ;
        assertTrue(server.getDataAccessPointRegistry().isRegistered("/ds")) ;
        server.start() ;
        competencyQuery("http://localhost:"+port+"/ds/competencyQuery", "SELECT * { ?s ?p ?o}", qExec-> {
            ResultSet rs = qExec.execSelect() ;
            assertFalse(rs.hasNext()) ;
        }) ;
        server.stop() ;
    }
*/
/*
    public FusekiServer defaultInit(){
        DatasetGraph dsg = dataset() ;
        int port = 3330 ;   // Default port.
        return FusekiServer.create().add("/ds", dsg).build() ;

    }
*/
/*
    static DatasetGraph dataset() {
    return DatasetGraphFactory.createTxnMem() ;
}
*/
/*
    static void competencyQuery(String URL, String competencyQuery, Consumer<QueryExecution> body) {
        try (QueryExecution qExec = QueryExecutionFactory.sparqlService(URL, competencyQuery) ) {
            body.accept(qExec);
        }
    }
    DatasetAccessorFactory.
        try (QueryExecution qExec = QueryExecutionFactory.sparqlService(URL, competencyQuery) ) {
            body.accept(qExec);
        }
        DatasetGraph dsg = dataset() ;
        int port = 3330 ;   // Default port.
        FusekiServer server = FusekiServer.create().add("/ds", dsg).build() ;

        assertTrue(server.getDataAccessPointRegistry().isRegistered("/ds")) ;

        server.start() ;
        competencyQuery("http://localhost:"+port+"/ds/competencyQuery", "SELECT * { ?s ?p ?o}", qExec-> {
            ResultSet rs = qExec.execSelect() ;
            assertFalse(rs.hasNext()) ;
        }) ;


        server.stop() ;
        new ListObjectsV2Request().withBucketName(uriKoma);

*/