package de.thb.koma.repository.sparql;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.apache.jena.fuseki.Fuseki;
import org.apache.jena.fuseki.embedded.FusekiServer;
import org.apache.jena.query.*;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.junit.Test;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

import static org.apache.jena.sparql.vocabulary.VocabTestQuery.query;

public class SparqlFusekiTest {
    private String bucketName = "ontology.thb.de";
    private String key = "koma-complex.owl";
    String uriService = "http://localhost:3030/ds/data";
    String uriKoma = "https://s3-us-west-2.amazonaws.com/ontology.thb.de/koma-complex.owl";
    String miniQuery = "SELECT ?s ?p ?o WHERE {\n" +
            "  ?s ?p ?o\n" +
            "}";
            String querySimple = "" +
            "PREFIX owl: <http://www.w3.org/2002/07/owl#>\n" +
            "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n" +
            "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n" +
            "\n" +
            "SELECT ?comp WHERE {\n" +
            "\t?comp rdf:type owl:Class .\n" +
            "}\n" +
            "ORDER BY ?label";
    String competencyQuery = "" +
            "PREFIX owl: <http://www.w3.org/2002/07/owl#>\n" +
            "PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>\n" +
            "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n" +
            "PREFIX skos: <http://www.w3.org/2004/02/skos/core#>\n" +
            "PREFIX koma: <https://s3-us-west-2.amazonaws.com/ontology.thb.de/koma-complex.owl#>\n" +
            "\n" +
            "\n" +
            "SELECT ?comp ?learn\n" +
            "  \tWHERE {\n" +
            "\t\t?comp rdf:type koma:Competency  .\n" +
            "\t\t?crec koma:associatedCompetency ?comp .\n" +
            "\t\t?learn rdf:type koma:Learner .\n" +
            "\t\t?crec koma:creator ?learn .\n" +
            "}\n" +
            "ORDER BY ASC (?comp) ";

    @Test public void getObject(){
        getObjectFromS3("/home/dado/.aws/credentials", bucketName, key);
    }
    @Test public void uploadLocalOWLToFuseki(){
        Model ontologyModel = ModelFactory.createOntologyModel();
        Model defModel = ModelFactory.createDefaultModel();
        try(FileInputStream in = new FileInputStream("/home/dado/projs/ba/sacwa/sparql/src/main/resources/koma-complex.owl")){
            defModel.read(in, null, "TTL");
        } catch (IOException e) {
            e.printStackTrace();
        }

        FusekiServer server = FusekiServer.create()
                .setPort(3030)
                .build();
        server.start();

        DatasetAccessor accessor = DatasetAccessorFactory.createHTTP("http://localhost:3030/data");
        accessor.add(defModel);

        QueryExecution queryExecution = QueryExecutionFactory.create(miniQuery);
        ResultSet resultSet = queryExecution.execSelect();
        for(String s : resultSet.getResultVars()){
            System.out.println(s);
        }

        server.stop();
    }

    private void getObjectFromS3(String credentials, String bucket, String file){
        GetObject accessor = new GetObject(credentials);
        accessor.get(bucket, file);
    }



}
/*
    @Test public void queryExternal(){
        InputStream in;
        DatasetAccessor accessor = DatasetAccessorFactory
                .createHTTP(uriService)
                .putModel(ModelFactory
                        .createDefaultModel()
                        .read(in, uriKoma, "RDF/XML"));
    }
    */
/*
    @Test public void embedded_01() {
        DatasetGraph dsg = dataset() ;
        int port = 3330 ;   // Default port.
        FusekiServer server = FusekiServer.create().add("/ds", dsg).build() ;
        assertTrue(server.getDataAccessPointRegistry().isRegistered("/ds")) ;
        server.start() ;
        competencyQuery("http://localhost:"+port+"/ds/competencyQuery", "SELECT * { ?s ?p ?o}", qExec-> {
            ResultSet rs = qExec.execSelect() ;
            assertFalse(rs.hasNext()) ;
        }) ;
        server.stop() ;
    }
*/
/*
    public FusekiServer defaultInit(){
        DatasetGraph dsg = dataset() ;
        int port = 3330 ;   // Default port.
        return FusekiServer.create().add("/ds", dsg).build() ;

    }
*/
/*
    static DatasetGraph dataset() {
    return DatasetGraphFactory.createTxnMem() ;
}
*/
/*
    static void competencyQuery(String URL, String competencyQuery, Consumer<QueryExecution> body) {
        try (QueryExecution qExec = QueryExecutionFactory.sparqlService(URL, competencyQuery) ) {
            body.accept(qExec);
        }
    }
    DatasetAccessorFactory.
        try (QueryExecution qExec = QueryExecutionFactory.sparqlService(URL, competencyQuery) ) {
            body.accept(qExec);
        }
        DatasetGraph dsg = dataset() ;
        int port = 3330 ;   // Default port.
        FusekiServer server = FusekiServer.create().add("/ds", dsg).build() ;

        assertTrue(server.getDataAccessPointRegistry().isRegistered("/ds")) ;

        server.start() ;
        competencyQuery("http://localhost:"+port+"/ds/competencyQuery", "SELECT * { ?s ?p ?o}", qExec-> {
            ResultSet rs = qExec.execSelect() ;
            assertFalse(rs.hasNext()) ;
        }) ;


        server.stop() ;
        new ListObjectsV2Request().withBucketName(uriKoma);

*/