package de.koma.repository;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.S3Object;

import java.util.StringJoiner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Handler implements RequestHandler<Object, String> {

    @Override
    public String handleRequest(Object input, Context context) {
        S3Object s3Object = AmazonS3ClientBuilder.standard()
                .build().getObject("ontology.thb.de", "koma-complex.owl");
        context.getLogger().log(String.valueOf(s3Object.getObjectContent()));
        return "done";
    }
}
