package de.thb.koma.service.sparql.jena;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.apache.jena.query.*;
import org.apache.jena.rdf.model.Literal;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.util.FileManager;
import org.junit.Test;


import static org.junit.Assert.*;

public class HandlerTest {
    String uriKoma = "https://s3-us-west-2.amazonaws.com/ontology.thb.de/koma-complex.owl";

    @Test public void query_01(){
        Model model = FileManager.get().loadModel("data/data.ttl");

        String queryString =
                "PREFIX foaf: <http://xmlns.com/foaf/0.1/> " +
                        "SELECT ?name WHERE { " +
                        "    ?person foaf:mbox <mailto:alice@example.org> . " +
                        "    ?person foaf:name ?name . " +
                        "}";
        Query query = QueryFactory.create(queryString);
        QueryExecution qexec = QueryExecutionFactory.create(query, model);
        try {
            ResultSet results = qexec.execSelect();
            while ( results.hasNext() ) {
                QuerySolution soln = results.nextSolution();
                Literal name = soln.getLiteral("name");
                System.out.println(name);
            }
        } finally {
            qexec.close();
        }

    }
}
